name: Build Xapian Static

on:
  workflow_dispatch:

env:
  # Build type
  BUILD_TYPE: Release

jobs:
  build-xapian:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            archive_format: tar.gz
            configure_args: ""
          - os: windows-latest
            platform: windows
            archive_format: zip
            configure_args: ""
          - os: macos-latest
            platform: macos
            archive_format: tar.gz
            configure_args: ""
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libmagic-dev \
            build-essential \
            autoconf \
            automake \
            libtool \
            git \
            zlib1g-dev \
            uuid-dev
        shell: bash

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows'
        run: |
          # Install MSYS2 for building
          choco install msys2 -y
          # Update MSYS2 and install required packages
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain autoconf automake libtool libmagic jq
        shell: bash

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos'
        run: |
          brew install autoconf automake libtool libmagic jq
        shell: bash

      - name: Get latest Xapian stable release tag
        id: xapian-version
        run: |
          # Get the latest release tag from Xapian GitHub repository
          LATEST_TAG=$(curl https://api.github.com/repos/xapian/xapian/tags | jq -r '.[0].name')
          if [ -z "$LATEST_TAG" ]; then
             echo "Error: Could not fetch Xapian release tag"
             exit 1
          fi
          echo "Latest Xapian release: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          # Extract version (remove 'v' prefix if present)
          VERSION=${LATEST_TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
        shell: bash

      - name: Cache Xapian source
        id: cache-xapian-source
        uses: actions/cache@v4
        with:
          path: xapian
          key: xapian-source-${{ steps.xapian-version.outputs.tag }}-${{ matrix.platform }}

      - name: Download Xapian source code
        if: steps.cache-xapian-source.outputs.cache-hit != 'true'
        run: |
          echo "Downloading Xapian ${{ steps.xapian-version.outputs.tag }}"
          git clone --depth 1 --branch ${{ steps.xapian-version.outputs.tag }} https://github.com/xapian/xapian.git
          if [ ! -d "xapian" ]; then
            echo "Error: Xapian source download failed"
            exit 1
          fi
          echo "Xapian source downloaded successfully"
        shell: bash

      - name: Bootstrap Xapian (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          cd xapian
          ./bootstrap
        shell: bash

      - name: Bootstrap Xapian (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd xapian
          C:\tools\msys64\usr\bin\bash -lc "cd /$(pwd -W | sed 's|:|/|; s|\\|/|g') && ./bootstrap"
        shell: bash

      - name: Configure Xapian (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          cd xapian
          ./configure \
            --prefix=${{ github.workspace }}/xapian-install \
            --enable-static=yes \
            --enable-shared=no \
            --disable-documentation \
            --disable-maintainer-mode \
            ${{ matrix.configure_args }}
        shell: bash

      - name: Configure Xapian (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd xapian
          INSTALL_PREFIX=$(echo '${{ github.workspace }}/xapian-install' | sed 's|\\|/|g; s|^\([A-Za-z]\):|/\L\1|')
          XAPIAN_DIR=$(pwd -W | sed 's|\\|/|g; s|^\([A-Za-z]\):|/\L\1|')
          C:\tools\msys64\usr\bin\bash -lc "cd $XAPIAN_DIR && ./configure --prefix=$INSTALL_PREFIX --enable-static=yes --enable-shared=no --disable-documentation --disable-maintainer-mode ${{ matrix.configure_args }}"
        shell: bash

      - name: Build Xapian (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          cd xapian
          make
        shell: bash

      - name: Build Xapian (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd xapian
          XAPIAN_DIR=$(pwd -W | sed 's|\\|/|g; s|^\([A-Za-z]\):|/\L\1|')
          C:\tools\msys64\usr\bin\bash -lc "cd $XAPIAN_DIR && make -j${NUMBER_OF_PROCESSORS:-4}"
        shell: bash

      - name: Install Xapian (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          cd xapian
          make install
        shell: bash

      - name: Install Xapian (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd xapian
          XAPIAN_DIR=$(pwd -W | sed 's|\\|/|g; s|^\([A-Za-z]\):|/\L\1|')
          C:\tools\msys64\usr\bin\bash -lc "cd $XAPIAN_DIR && make install"
        shell: bash

      - name: Verify static build
        run: |
          echo "Checking Xapian static library..."
          if [ "${{ matrix.platform }}" == "windows" ]; then
            find ${{ github.workspace }}/xapian-install -name "*.a" -o -name "*.lib" | head -10
          else
            find ${{ github.workspace }}/xapian-install -name "*.a" | head -10
          fi
        shell: bash

      - name: Create build artifact
        run: |
          cd ${{ github.workspace }}
          if [ "${{ matrix.archive_format }}" == "zip" ]; then
            # Use PowerShell for Windows zip creation
            powershell.exe -Command "Compress-Archive -Path 'xapian-install\\*' -DestinationPath 'xapian-static-${{ steps.xapian-version.outputs.version }}-${{ matrix.platform }}.zip' -Force"
          else
            tar -czf xapian-static-${{ steps.xapian-version.outputs.version }}-${{ matrix.platform }}.tar.gz -C xapian-install .
          fi
        shell: bash

      - name: Upload Xapian static build
        uses: actions/upload-artifact@v4
        with:
          name: xapian-static-${{ steps.xapian-version.outputs.version }}-${{ matrix.platform }}
          path: xapian-static-${{ steps.xapian-version.outputs.version }}-${{ matrix.platform }}.${{ matrix.archive_format }}
          retention-days: 30

      - name: Display build summary
        run: |
          echo "## Xapian Build Summary (${{ matrix.platform }})" >> $GITHUB_STEP_SUMMARY
          echo "- **Platform**: ${{ matrix.platform }}" >> $GITHUB_STEP_SUMMARY
          echo "- **OS**: ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Xapian Version**: ${{ steps.xapian-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Type**: Static" >> $GITHUB_STEP_SUMMARY
          echo "- **Static Build**: Enabled (--enable-static=yes)" >> $GITHUB_STEP_SUMMARY
          echo "- **Shared Build**: Disabled (--enable-shared=no)" >> $GITHUB_STEP_SUMMARY
          echo "- **Archive Format**: ${{ matrix.archive_format }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Configure Args" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo '--enable-static=yes --enable-shared=no --disable-documentation ${{ matrix.configure_args }}' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installed Components" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          find ${{ github.workspace }}/xapian-install -type f -name "*.a" 2>/dev/null | head -20 >> $GITHUB_STEP_SUMMARY || true
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        shell: bash
